name: Deploy Movie Recommender to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Movie_Recommender_System

            echo "Pull latest code..."
            git pull origin main

            echo "Build Docker image..."
            docker build -t movie-recommender .

            echo "Stop old container..."
            docker stop movie-app || true
            docker rm movie-app || true

            echo "Run new container..."
            docker run -d \
              --name movie-app \
              --restart unless-stopped \
              -p 8501:8501 \
              --env-file .env \
              movie-recommender

            echo "Deployment completed successfully!"
            